EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306
OLED_DRIVER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = yes

EXTRAFLAGS += -flto
