SPLIT_KEYBOARD = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = yes

EXTRAFLAGS += -flto
